### ISSUE TITLE
Couldn't run the code

### ISSUE THREAD

**Issue by Twizwei** [scott-yjyang/ViWS-Net#2]
bash-4.4$ python eval_derain.py --data_dir Dataset/RainMotion/Test --model weights/best.pth --output Results
Traceback (most recent call last):
  File "/fs/vulcan-projects/denso_obrm/ViWS-Net/eval_derain.py", line 242, in <module>
    eval()
  File "/fs/vulcan-projects/denso_obrm/ViWS-Net/eval_derain.py", line 133, in eval
    centre_frame = forward_crop(neigbor, model, lq_size=512, overlap=16).cuda()
  File "/fs/vulcan-projects/denso_obrm/ViWS-Net/crop_validation.py", line 126, in forward_crop
    = x_crops[B_start: B_end, :, pi_start: pi_end, pj_start: pj_end]
RuntimeError: The expanded size of the tensor (480) must match the existing size (32) at non-singleton dimension 2.  Target sizes: [1, 3, 480, 504].  Tensor sizes: [3, 32, 504]

Looks like there is a bug with the way you crop the images

**Comment by mlh68** [comment]
Hello,have you solved this problem?

**Comment by sue20020124** [comment]
me too!

**Comment by yulong143** [comment]
> me too!
